### ISSUE TITLE
AWS device farm gives error that application does not exist 

### ISSUE THREAD

**Issue by ghost** [names144/RNDeviceFarm#1]
```
[DEVICEFARM] Setting up your device. This usually takes 2-3 minutes.
[DEVICEFARM] ########### Start executing testspec ###########
 
 
[DEVICEFARM] ########### Entering phase install ###########
 
[DeviceFarm] export APPIUM_VERSION=1.9.1
[DeviceFarm] avm $APPIUM_VERSION
  [36m    exists[0m : [90m1.9.1[0m
[DeviceFarm] ln -s /usr/local/avm/versions/$APPIUM_VERSION/node_modules/.bin/appium  /usr/local/avm/versions/$APPIUM_VERSION/node_modules/appium/bin/appium.js
ln: failed to create symbolic link ‘/usr/local/avm/versions/1.9.1/node_modules/appium/bin/appium.js’: File exists
[DeviceFarm] echo "Navigate to test package directory"
Navigate to test package directory
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH
[DeviceFarm] npm install *.tgz

> fibers_node_v8@3.1.5 preinstall /tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/@wdio/sync/node_modules/fibers_node_v8
> node preinstall.js


> fibers_node_v8@3.1.5 install /tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/@wdio/sync/node_modules/fibers_node_v8
> node build.js

ignore install

> fibers@4.0.3 install /tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/@wdio/sync/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/@wdio/sync/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/@wdio/sync/node_modules/fibers/build'
Installed in `/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/@wdio/sync/node_modules/fibers/bin/linux-x64-67-glibc/fibers.node`
npm WARN saveError ENOENT: no such file or directory, open '/tmp/scratch27VgXy.scratch/test-packagejCr6p5/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/integration/node_modules/@wdio/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/tmp/scratch27VgXy.scratch/test-packagejCr6p5/package.json'
npm WARN test-packagejCr6p5 No description
npm WARN test-packagejCr6p5 No repository field.
npm WARN test-packagejCr6p5 No README data
npm WARN test-packagejCr6p5 No license field.

+ integration@1.0.0
added 484 packages from 242 contributors and audited 485 packages in 20.948s
found 0 vulnerabilities

 
[DEVICEFARM] ########### Entering phase pre_test ###########
 
[DeviceFarm] echo "Start appium server"
Start appium server
[DeviceFarm] appium --log-timestamp --device-name $DEVICEFARM_DEVICE_NAME --platform-name $DEVICEFARM_DEVICE_PLATFORM_NAME --app $DEVICEFARM_APP_PATH --automation-name UiAutomator2 --udid $DEVICEFARM_DEVICE_UDID --chromedriver-executable $DEVICEFARM_CHROMEDRIVER_EXECUTABLE  >> $DEVICEFARM_LOG_DIR/appiumlog.txt 2>&1 &
[DeviceFarm] start_appium_timeout=0; while [ true ]; do
    if [ $start_appium_timeout -gt 60 ];
    then
        echo "appium server never started in 60 seconds. Exiting";
        exit 1;
    fi;
    grep -i "Appium REST http interface listener started on 0.0.0.0:4723" $DEVICEFARM_LOG_DIR/appiumlog.txt >> /dev/null 2>&1;
    if [ $? -eq 0 ];
    then
        echo "Appium REST http interface listener started on 0.0.0.0:4723";
        break;
    else
        echo "Waiting for appium server to start. Sleeping for 1 second";
        sleep 1;
        start_appium_timeout=$((start_appium_timeout+1));
    fi;
done; 
Waiting for appium server to start. Sleeping for 1 second
Waiting for appium server to start. Sleeping for 1 second
Appium REST http interface listener started on 0.0.0.0:4723
 
[DEVICEFARM] ########### Entering phase test ###########
 
[DeviceFarm] echo "Navigate to test source code"
Navigate to test source code
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH/node_modules/*
[DeviceFarm] ls
appium.android.yml
appium.ios.yml
node_modules
package.json
test
wdio.android.conf.js
wdio.android.local.conf.js
wdio.ios.conf.js
wdio.ios.local.conf.js
wdio.shared.conf.js
[DeviceFarm] echo "Start Appium Node test"
Start Appium Node test
[DeviceFarm] npm run test:android

> integration@1.0.0 test:android /tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration
> npx wdio ./wdio.android.conf.js


Execution of 1 spec files started at 2021-06-10T12:11:08.368Z

2021-06-10T12:11:08.373Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-06-10T12:11:08.379Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./wdio.android.conf.js
[0-0] 2021-06-10T12:11:08.831Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in undefined - /test/specs/App.test.js
[0-0] 2021-06-10T12:11:08.921Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-06-10T12:11:08.922Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2021-06-10T12:11:08.925Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2021-06-10T12:11:08.925Z INFO webdriver: DATA { capabilities: { alwaysMatch: {}, firstMatch: [ {} ] },
  desiredCapabilities: {} }
[0-0] 2021-06-10T12:11:18.940Z WARN webdriver: Request failed due to ESOCKETTIMEDOUT
[0-0] 2021-06-10T12:11:18.941Z INFO webdriver: Retrying 1/3
2021-06-10T12:11:18.941Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
2021-06-10T12:11:18.941Z INFO webdriver: DATA { capabilities: { alwaysMatch: {}, firstMatch: [ {} ] },
  desiredCapabilities: {} }
[0-0] 2021-06-10T12:11:28.954Z WARN webdriver: Request failed due to ESOCKETTIMEDOUT
[0-0] 2021-06-10T12:11:28.954Z INFO webdriver: Retrying 2/3
2021-06-10T12:11:28.954Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2021-06-10T12:11:28.954Z INFO webdriver: DATA { capabilities: { alwaysMatch: {}, firstMatch: [ {} ] },
  desiredCapabilities: {} }
[0-0] 2021-06-10T12:11:35.885Z DEBUG webdriver: request failed due to response error: unknown error
[0-0] 2021-06-10T12:11:35.886Z WARN webdriver: Request failed due to An unknown server-side error occurred while processing the command. Original error: /tmp/scratch27VgXy.scratch/share-0QPtmN.scratch/app-x6NpjR.apk file doesn't exist.
[0-0] 2021-06-10T12:11:35.886Z INFO webdriver: Retrying 3/3
2021-06-10T12:11:35.886Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2021-06-10T12:11:35.886Z INFO webdriver: DATA { capabilities: { alwaysMatch: {}, firstMatch: [ {} ] },
  desiredCapabilities: {} }
[0-0] 2021-06-10T12:11:35.947Z DEBUG webdriver: request failed due to response error: unknown error
[0-0] 2021-06-10T12:11:35.947Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: The application at '/tmp/scratch27VgXy.scratch/share-0QPtmN.scratch/app-x6NpjR.apk' does not exist or is not accessible
    at getErrorFromResponseBody (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:277:13)
2021-06-10T12:11:35.948Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: The application at '/tmp/scratch27VgXy.scratch/share-0QPtmN.scratch/app-x6NpjR.apk' does not exist or is not accessible
    at getErrorFromResponseBody (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:277:13)
[0-0] 2021-06-10T12:11:35.949Z ERROR @wdio/runner: Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: The application at '/tmp/scratch27VgXy.scratch/share-0QPtmN.scratch/app-x6NpjR.apk' does not exist or is not accessible
    at startWebDriverSession (/tmp/scratch27VgXy.scratch/test-packagejCr6p5/node_modules/integration/node_modules/webdriverio/node_modules/webdriver/build/utils.js:45:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
[0-0] Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: The application at '/tmp/scratch27VgXy.scratch/share-0QPtmN.scratch/app-x6NpjR.apk' does not exist or is not accessible
2021-06-10T12:11:36.057Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in undefined - /test/specs/App.test.js
2021-06-10T12:11:36.058Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:27 

2021-06-10T12:11:36.060Z INFO @wdio/local-runner: Shutting down spawned worker
2021-06-10T12:11:36.312Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-06-10T12:11:36.313Z INFO @wdio/local-runner: shutting down
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integration@1.0.0 test:android: `npx wdio ./wdio.android.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the integration@1.0.0 test:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/device-farm/.npm/_logs/2021-06-10T12_11_36_323Z-debug.log
 
[DEVICEFARM] ########### Entering phase post_test ###########
 
 
[DEVICEFARM] ########### Finish executing testspec ###########
 
[DEVICEFARM] ########### Setting upload permissions ###########
 
 
[DEVICEFARM] Tearing down your device. Your tests report will come shortly.

```

**Comment by Yonas21** [comment]
upload the application before the start the test in configure step in aws device farm.
